import type { Recruitment } from "./db/recruitments";

export const mockRecruitments: Recruitment[] = [
  {
    id: "r1",
    event_id: "1",
    organizer_id: "o1",
    type: "volunteer",
    title: "フリーマーケット 受付スタッフ",
    description: "春のフリーマーケットの受付を担当していただける方を募集します。",
    role: "受付",
    time_slot: "10:00-12:00",
    compensation_type: "証明書",
    compensation_note: "活動証明書を発行します",
    pay_type: null,
    pay_amount: null,
    work_hours: null,
    work_content: null,
    payment_method: null,
    employer_name: null,
    employment_type: null,
    work_conditions: null,
    application_method: null,
    tech_slot: null,
    deliverable_scope: null,
    created_at: "2025-02-01T10:00:00Z",
    updated_at: "2025-02-01T10:00:00Z",
  },
  {
    id: "r2",
    event_id: null,
    organizer_id: "o2",
    type: "paid_spot",
    title: "繁忙期 カフェスタッフ（日払い）",
    description: "週末の混雑時のみお手伝いいただけるスタッフを募集しています。",
    role: null,
    time_slot: null,
    compensation_type: null,
    compensation_note: null,
    pay_type: "謝礼",
    pay_amount: 1200,
    work_hours: "10:00-18:00（休憩1h）",
    work_content: "ホール、レジ業務",
    payment_method: "当日現金",
    employer_name: "喫茶ポプラ",
    employment_type: null,
    work_conditions: null,
    application_method: null,
    tech_slot: null,
    deliverable_scope: null,
    created_at: "2025-02-05T09:00:00Z",
    updated_at: "2025-02-05T09:00:00Z",
  },
  {
    id: "r3",
    event_id: "1",
    organizer_id: "o1",
    type: "tech_volunteer",
    title: "SNS投稿文の作成支援",
    description: "イベント告知用のSNS投稿文を作成していただける方を募集します。",
    tech_role: "web",
    role: null,
    time_slot: null,
    compensation_type: null,
    compensation_note: null,
    pay_type: null,
    pay_amount: null,
    work_hours: null,
    work_content: null,
    payment_method: null,
    employer_name: null,
    employment_type: null,
    work_conditions: null,
    application_method: null,
    tech_slot: "light",
    deliverable_scope: "Instagram用投稿文 2本",
    created_at: "2025-02-08T14:00:00Z",
    updated_at: "2025-02-08T14:00:00Z",
  },
];
